
USE patienceBank_db;
CREATE TABLE IF NOT EXISTS articles (
  id            INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title         VARCHAR(512) NOT NULL,
  link          VARCHAR(512) NOT NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
