services:
  go-api:
    container_name: patienceBank_api
    build: 
      context: ./api
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/go/src/app
    networks:
      - patienceBank-networks
  db:
    image: mysql:8.0
    container_name: patienceBank_db
    build: ./mysql
    tty: true
    platform: linux/amd64
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "8000:3306"
    volumes:
      - patience_test_volumes:/var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d
    networks:
      - patienceBank-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  patience_test_volumes:
    name: patience_test_volumes
networks:
  patienceBank-networks:
    external: true